version: '3'

services:
  app-database:
    tty: true
    image: 'postgres:15.4'
    env_file:
      - env/run/app-database.env
    ports:
      - "5432:5432"
    volumes:
      - app-database:/var/lib/postgresql/data/

volumes:
  app-database:
