version: '3'

services:
  primary-database:
    tty: true
    image: 'postgres:15.4'
    env_file:
      - env/run/primary-database.env
    ports:
      - "5432:5432"
    volumes:
      - primary-database:/var/lib/postgresql/data/

volumes:
  primary-database:
