version: '3'

services:
  backend:
    tty: true
    build: ./apps/backend/
    container_name: "backend"
    env_file:
      - ./apps/backend/.env
    ports:
      - "4000:4000"
      - "4001:4001"
    volumes:
      - ./apps/backend/src:/app/src
    command: pnpm run start:dev:memory