version: '3'

services:
  backend:
    tty: true
    build: applications/backend/
    depends_on:
      - primary-database
    env_file:
      - applications/backend/.env
    container_name: "backend"
    ports:
      - "4000:4000"
      - "4001:4001"
    networks:
      - backend-network

  primary-database:
    tty: true
    image: 'postgres:15.4'
    container_name: "primary-database"
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - backend-network
    volumes:
      - primary-database:/var/lib/postgresql/data/

volumes:
  primary-database:

networks:
  backend-network: